XCPNG-486: Fix for ENOMEM error in DxeIplPeim
This patch fix an error that materialise as:

> AllocatePages failed: No 0x8400 Pages is available.
> There is only left 0x3AA8 pages memory resource to be allocated.
> ERROR: Out of aligned pages

One some system, with XCP-ng's OvmfXen, we can be in a position were
PhysicalAddressBits == 45 but Page1GSupport==FALSE, which lead to a
huge amount of memory needed to allocate the page tables:

> AddressBits=45 5LevelPaging=0 1GPage=0
> Pml5=1 Pml4=64 Pdp=512 TotalPage=32833

The added patch explain where the allocated memory is gone, and why,
and allocate enough space for it.

Signed-off-by: Anthony PERARD <anthony.perard@vates.tech>